import 'dart:async';
import 'package:flutter/material.dart' show ElevatedButton, GestureDetector;
import 'package:flutter_test/flutter_test.dart';
import 'package:provider/provider.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:mockito/annotations.dart' show GenerateMocks;

import 'package:tictactoe/main.dart' show MyApp;
import 'package:tictactoe/firebase_service.dart' show FirebaseService;
import 'package:tictactoe/game_controller.dart';
import 'package:tictactoe/settings_controller.dart';
import 'package:tictactoe/sound_manager.dart' show SoundManager;
import 'package:tictactoe/auth_controller.dart';
import 'package:tictactoe/game_screen.dart';

import 'package:mockito/mockito.dart' show when;
import 'widget_test.mocks.dart';
//
// 1. Generate mocks for FirebaseService and User
@GenerateMocks([FirebaseService, User])

void main() {
  testWidgets('Tic-Tac-Toe game test', (WidgetTester tester) async {
    // 1. Setup Mocks (Ensure widget_test.mocks.dart is generated by running `flutter pub run build_runner build`)
    final mockFirebaseService = MockFirebaseService();
    final mockUser = MockUser();
    final authStateController = StreamController<User?>();

    // Mock the authStateChanges stream
    when(mockFirebaseService.authStateChanges).thenAnswer((_) => authStateController.stream);
    when(mockFirebaseService.currentUser).thenReturn(mockUser);

    // 2. Setup Controllers and Services, similar to main.dart
    final settingsController = SettingsController();
    await settingsController.loadSettings();
    final soundManager = SoundManager(settingsController);
    await soundManager.init();

    // 3. Build our app ONCE with all necessary providers
    await tester.pumpWidget(
      MultiProvider(
        providers: [
          ChangeNotifierProvider.value(value: settingsController),
          Provider<FirebaseService>.value(value: mockFirebaseService),
          ChangeNotifierProvider(create: (_) => AuthController(mockFirebaseService)),
          Provider<SoundManager>(create: (_) => soundManager, dispose: (_, manager) => manager.dispose()),
          ChangeNotifierProxyProvider<SettingsController, GameController>(
            update: (context, settings, previous) {
              // Ensure the previous controller is not null and update its dependencies.
              previous?.updateDependencies(settings);
              // FIXED: Added context.read<FirebaseService>() as the 3rd argument
              return previous ?? GameController(
                context.read<SoundManager>(),
                settings,
                context.read<FirebaseService>(),
              );
            },
            // FIXED: Added context.read<FirebaseService>() as the 3rd argument
            create: (context) => GameController(
              context.read<SoundManager>(),
              context.read<SettingsController>(),
              context.read<FirebaseService>(),
            ),
          ),
        ],
        child: const MyApp(isPrimaryInstance: true),
      ),
    );

    // 4. Simulate user login
    // The app starts on the AuthScreen. We need to simulate a login.
    authStateController.add(mockUser);
    await tester.pumpAndSettle(); // Wait for navigation to GameScreen

    // Verify the initial state of the game.
    expect(find.text("Player X's Turn"), findsOneWidget, reason: "Game should start with Player X's turn");
    expect(find.text('X'), findsNothing);
    expect(find.text('O'), findsNothing);

    // Find all the game board cells (GestureDetectors).
    final cells = find.byType(GestureDetector);
    expect(cells, findsNWidgets(9));

    // Player X takes the center square.
    await tester.tap(cells.at(4));
    await tester.pump();

    // Verify the board updated.
    expect(find.text('X'), findsOneWidget);
    expect(find.text("Player O's Turn"), findsOneWidget);

    // Player O takes the top-left square.
    await tester.tap(cells.at(0));
    await tester.pump();

    // Verify the board updated.
    expect(find.text('O'), findsOneWidget);
    expect(find.text("Player X's Turn"), findsOneWidget);

    // Find the "Play Again" button (it shouldn't exist yet).
    expect(find.text('Play Again'), findsNothing);

    // Continue game to a win condition for X
    // X: 4, O: 0
    await tester.tap(cells.at(1)); // X
    await tester.pump();
    await tester.tap(cells.at(2)); // O
    await tester.pump();
    await tester.tap(cells.at(7)); // X
    await tester.pump();

    // Verify the win state
    expect(find.text('Player X Wins!'), findsOneWidget);

    // Verify the "Play Again" button now exists
    final playAgainButton = find.widgetWithText(ElevatedButton, 'Play Again');
    expect(playAgainButton, findsOneWidget);

    // Tap "Play Again" and verify the game resets
    await tester.tap(playAgainButton);
    await tester.pump();

    expect(find.text("Player X's Turn"), findsOneWidget);
    expect(find.text('X'), findsNothing);
  });
}
