import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:window_manager/window_manager.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'auth_controller.dart';
import 'auth_screen.dart';
import 'firebase_service.dart';
import 'game_screen.dart';
import 'window_setup.dart';
import 'settings_controller.dart';
import 'sound_manager.dart';
import 'firebase_options.dart'; // This will be generated by flutterfire_cli

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ARCHITECTURAL FIX: Centralize initialization to prevent race conditions.
  // 1. Initialize window_manager first, as it can trigger other native plugin loads.
  await windowManager.ensureInitialized();

  // Load environment variables before any other Firebase or app setup.
  // This resolves the NotInitializedError.
  await dotenv.load();

  // 2. Initialize Firebase now that environment variables are loaded.
  await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform); // Uncomment after running flutterfire_cli
  await configureWindow();

  // Initialize controllers and services
  final settingsController = SettingsController();
  await settingsController.loadSettings();

  // Pass the settings controller to the sound manager
  final soundManager = SoundManager(settingsController);
  await soundManager.init();

  final firebaseService = FirebaseService();

  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider.value(value: settingsController),
        Provider.value(value: firebaseService),
        ChangeNotifierProvider(
            create: (context) => AuthController(firebaseService)),
        // Provide SoundManager and ensure its dispose method is called.
        Provider<SoundManager>(
          create: (_) => soundManager,
          dispose: (_, manager) => manager.dispose(),
        ),
        // Use ChangeNotifierProxyProvider to create GameController with dependencies.
        ChangeNotifierProxyProvider<SettingsController, GameController>(
          create: (context) => GameController(
              context.read<SoundManager>(), context.read<SettingsController>()),
          update: (context, settings, previousGameController) {
            if (settings.resetGameRequested) {
              previousGameController?.initializeGame();
              settings.consumeGameResetRequest();
            }
            previousGameController?.updateDependencies(settings);
            return previousGameController!;
          },
        ),
      ],
      child: const MyApp(),
    ),
  );
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    final settings = context.watch<SettingsController>();
    return MaterialApp(
      title: 'Ultimate Tic-Tac-Toe',
      theme: settings.themeData.copyWith(
        // Ensure text on elevated buttons is readable
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ButtonStyle(
            foregroundColor:
                WidgetStateProperty.all(settings.themeData.colorScheme.onPrimary),
          ),
        ),
      ),
      home: StreamBuilder<User?>(
        stream: context.read<FirebaseService>().authStateChanges,
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Scaffold(
              body: Center(child: CircularProgressIndicator()),
            );
          }
          return snapshot.hasData ? const TicTacToeGame() : const AuthScreen();
        },
      ),
      debugShowCheckedModeBanner: false,
    );
  }
}
//This a modification test